export const personalInfo = {
  name: 'Arron',
  title: 'Full Stack Developer',
  tagline: 'Building digital experiences that matter',
  bio: 'I am a passionate full-stack developer with expertise in building modern, scalable web applications. I love turning complex problems into simple, elegant solutions.',
  location: 'London, UK',
  email: 'arronkukadia1@gmail.com',
  linkedin: 'https://uk.linkedin.com/in/arron-kukadia',
  github: 'https://github.com/arron-kukadia',
  instagram: 'https://www.instagram.com/ak1photography',
  cvUrl: '/cv.pdf',
  skills: [
    'JavaScript',
    'TypeScript',
    'React',
    'Next.js',
    'Node.js',
    'Python',
    'PostgreSQL',
    'MongoDB',
    'GraphQL',
    'Docker',
    'AWS',
    'TailwindCSS',
  ],
}
